In [1]:
import numpy as np
import pandas as pd

data = pd.read_csv(r"D:\Oladimeji\Data Science\DataSet\Kaggle\Healthcare Providers.csv")

In [2]:
# Checking the number of rows and columns to clean
data.shape

(100000, 27)

In [3]:
# To get the overview of the columns in the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   index                                                     100000 non-null  int64
 1   National Provider Identifier                              100000 non-null  int64
 2   Last Name/Organization Name of the Provider               100000 non-null  object
 3   First Name of the Provider                                95745 non-null   object
 4   Middle Initial of the Provider                            70669 non-null   object
 5   Credentials of the Provider                               92791 non-null   object
 6   Gender of the Provider                                    95746 non-null   object
 7   Entity Type of the Provider                               100000 non-null  object
 8   Street Address 1 of the Provider                          100000 non-null  object
 9   Street Address 2 of the Provider                          40637 non-null   object
 10  City of the Provider                                      100000 non-null  object
 11  Zip Code of the Provider                                  100000 non-null  float64
 12  State Code of the Provider                                100000 non-null  object
 13  Country Code of the Provider                              100000 non-null  object
 14  Provider Type                                             100000 non-null  object
 15  Medicare Participation Indicator                          100000 non-null  object
 16  Place of Service                                          100000 non-null  object
 17  HCPCS Code                                                100000 non-null  object
 18  HCPCS Description                                         100000 non-null  object
 19  HCPCS Drug Indicator                                      100000 non-null  object
 20  Number of Services                                        100000 non-null  object
 21  Number of Medicare Beneficiaries                          100000 non-null  object
 22  Number of Distinct Medicare Beneficiary/Per Day Services  100000 non-null  object
 23  Average Medicare Allowed Amount                           100000 non-null  object
 24  Average Submitted Charge Amount                           100000 non-null  object
 25  Average Medicare Payment Amount                           100000 non-null  object
 26  Average Medicare Standardized Amount                      100000 non-null  object
dtypes: float64(1), int64(2), object(24)
memory usage: 20.6+ MB

In [4]:
# To get the sum of all the missing values in the columns
data.isna().sum()

index                                                           0
National Provider Identifier                                    0
Last Name/Organization Name of the Provider                     0
First Name of the Provider                                   4255
Middle Initial of the Provider                              29331
Credentials of the Provider                                  7209
Gender of the Provider                                       4254
Entity Type of the Provider                                     0
Street Address 1 of the Provider                                0
Street Address 2 of the Provider                            59363
City of the Provider                                            0
Zip Code of the Provider                                        0
State Code of the Provider                                      0
Country Code of the Provider                                    0
Provider Type                                                   0
Medicare Participation Indicator                                0
Place of Service                                                0
HCPCS Code                                                      0
HCPCS Description                                               0
HCPCS Drug Indicator                                            0
Number of Services                                              0
Number of Medicare Beneficiaries                                0
Number of Distinct Medicare Beneficiary/Per Day Services        0
Average Medicare Allowed Amount                                 0
Average Submitted Charge Amount                                 0
Average Medicare Payment Amount                                 0
Average Medicare Standardized Amount                            0
dtype: int64

In [5]:
# Dropping the column because Street Address 1 contains more informations needed
data.drop(columns = ["Street Address 2 of the Provider"], inplace = True)

In [6]:
data.isna().sum()

index                                                           0
National Provider Identifier                                    0
Last Name/Organization Name of the Provider                     0
First Name of the Provider                                   4255
Middle Initial of the Provider                              29331
Credentials of the Provider                                  7209
Gender of the Provider                                       4254
Entity Type of the Provider                                     0
Street Address 1 of the Provider                                0
City of the Provider                                            0
Zip Code of the Provider                                        0
State Code of the Provider                                      0
Country Code of the Provider                                    0
Provider Type                                                   0
Medicare Participation Indicator                                0
Place of Service                                                0
HCPCS Code                                                      0
HCPCS Description                                               0
HCPCS Drug Indicator                                            0
Number of Services                                              0
Number of Medicare Beneficiaries                                0
Number of Distinct Medicare Beneficiary/Per Day Services        0
Average Medicare Allowed Amount                                 0
Average Submitted Charge Amount                                 0
Average Medicare Payment Amount                                 0
Average Medicare Standardized Amount                            0
dtype: int64

In [7]:
# Getting the firt 5 rows from the data table
data.head()

,index,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,City of the Provider,...,HCPCS Code,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount
0,8774979,1891106191,UPADHYAYULA,SATYASREE,NaN,M.D.,F,I,1402 S GRAND BLVD,SAINT LOUIS,...,99223,"Initial hospital inpatient care, typically 70 ...",N,27,24,27,200.58777778,305.21111111,157.26222222,160.90888889
1,3354385,1346202256,JONES,WENDY,P,M.D.,F,I,2950 VILLAGE DR,FAYETTEVILLE,...,G0202,"Screening mammography, bilateral (2-view study...",N,175,175,175,123.73,548.8,118.83,135.31525714
2,3001884,1306820956,DUROCHER,RICHARD,W,DPM,M,I,20 WASHINGTON AVE,NORTH HAVEN,...,99348,"Established patient home visit, typically 25 m...",N,32,13,32,90.65,155,64.4396875,60.5959375
3,7594822,1770523540,FULLARD,JASPER,NaN,MD,M,I,5746 N BROADWAY ST,KANSAS CITY,...,81002,"Urinalysis, manual test",N,20,18,20,3.5,5,3.43,3.43
4,746159,1073627758,PERROTTI,ANTHONY,E,DO,M,I,875 MILITARY TRL,JUPITER,...,96372,Injection beneath the skin or into muscle for ...,N,33,24,31,26.52,40,19.539393939,19.057575758

In [8]:
# Getting the number of the missing value in the provider gender column
data["Gender of the Provider"].value_counts()

Gender of the Provider
M    66641
F    29105
Name: count, dtype: int64

In [9]:
# To replace the null values with unknown to clean the gender column
data.fillna({"Gender of the Provider":"UNKNOWN"}, inplace = True)

In [10]:
# Doing the value count to confirm the changes
data["Gender of the Provider"].value_counts()

Gender of the Provider
M          66641
F          29105
UNKNOWN     4254
Name: count, dtype: int64

In [11]:
# Cofiming the changes on the original data
data.isna().sum()

index                                                           0
National Provider Identifier                                    0
Last Name/Organization Name of the Provider                     0
First Name of the Provider                                   4255
Middle Initial of the Provider                              29331
Credentials of the Provider                                  7209
Gender of the Provider                                          0
Entity Type of the Provider                                     0
Street Address 1 of the Provider                                0
City of the Provider                                            0
Zip Code of the Provider                                        0
State Code of the Provider                                      0
Country Code of the Provider                                    0
Provider Type                                                   0
Medicare Participation Indicator                                0
Place of Service                                                0
HCPCS Code                                                      0
HCPCS Description                                               0
HCPCS Drug Indicator                                            0
Number of Services                                              0
Number of Medicare Beneficiaries                                0
Number of Distinct Medicare Beneficiary/Per Day Services        0
Average Medicare Allowed Amount                                 0
Average Submitted Charge Amount                                 0
Average Medicare Payment Amount                                 0
Average Medicare Standardized Amount                            0
dtype: int64

In [12]:
# Filling all missing values in the initial columns with 'No Initials'. It can not be guessed
data.fillna({"Middle Initial of the Provider": "No Initial"}, inplace = True)

In [13]:
data.isna().sum()

index                                                          0
National Provider Identifier                                   0
Last Name/Organization Name of the Provider                    0
First Name of the Provider                                  4255
Middle Initial of the Provider                                 0
Credentials of the Provider                                 7209
Gender of the Provider                                         0
Entity Type of the Provider                                    0
Street Address 1 of the Provider                               0
City of the Provider                                           0
Zip Code of the Provider                                       0
State Code of the Provider                                     0
Country Code of the Provider                                   0
Provider Type                                                  0
Medicare Participation Indicator                               0
Place of Service                                               0
HCPCS Code                                                     0
HCPCS Description                                              0
HCPCS Drug Indicator                                           0
Number of Services                                             0
Number of Medicare Beneficiaries                               0
Number of Distinct Medicare Beneficiary/Per Day Services       0
Average Medicare Allowed Amount                                0
Average Submitted Charge Amount                                0
Average Medicare Payment Amount                                0
Average Medicare Standardized Amount                           0
dtype: int64

In [14]:
# Replacing the missing name of the provider with the national provider identification because it is a unique number
data["First Name of the Provider"] = data["First Name of the Provider"].fillna(data["National Provider Identifier"].astype(str))

In [15]:
# Looking at the remaining column with missing values
data.isna().sum()

index                                                          0
National Provider Identifier                                   0
Last Name/Organization Name of the Provider                    0
First Name of the Provider                                     0
Middle Initial of the Provider                                 0
Credentials of the Provider                                 7209
Gender of the Provider                                         0
Entity Type of the Provider                                    0
Street Address 1 of the Provider                               0
City of the Provider                                           0
Zip Code of the Provider                                       0
State Code of the Provider                                     0
Country Code of the Provider                                   0
Provider Type                                                  0
Medicare Participation Indicator                               0
Place of Service                                               0
HCPCS Code                                                     0
HCPCS Description                                              0
HCPCS Drug Indicator                                           0
Number of Services                                             0
Number of Medicare Beneficiaries                               0
Number of Distinct Medicare Beneficiary/Per Day Services       0
Average Medicare Allowed Amount                                0
Average Submitted Charge Amount                                0
Average Medicare Payment Amount                                0
Average Medicare Standardized Amount                           0
dtype: int64

In [16]:
# The first ten information in the variable "data"
data.head(10)

,index,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,City of the Provider,...,HCPCS Code,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount
0,8774979,1891106191,UPADHYAYULA,SATYASREE,No Initial,M.D.,F,I,1402 S GRAND BLVD,SAINT LOUIS,...,99223,"Initial hospital inpatient care, typically 70 ...",N,27,24,27,200.58777778,305.21111111,157.26222222,160.90888889
1,3354385,1346202256,JONES,WENDY,P,M.D.,F,I,2950 VILLAGE DR,FAYETTEVILLE,...,G0202,"Screening mammography, bilateral (2-view study...",N,175,175,175,123.73,548.8,118.83,135.31525714
2,3001884,1306820956,DUROCHER,RICHARD,W,DPM,M,I,20 WASHINGTON AVE,NORTH HAVEN,...,99348,"Established patient home visit, typically 25 m...",N,32,13,32,90.65,155,64.4396875,60.5959375
3,7594822,1770523540,FULLARD,JASPER,No Initial,MD,M,I,5746 N BROADWAY ST,KANSAS CITY,...,81002,"Urinalysis, manual test",N,20,18,20,3.5,5,3.43,3.43
4,746159,1073627758,PERROTTI,ANTHONY,E,DO,M,I,875 MILITARY TRL,JUPITER,...,96372,Injection beneath the skin or into muscle for ...,N,33,24,31,26.52,40,19.539393939,19.057575758
5,3443985,1346571551,PUGH,JOHN,R,DPT,M,I,504 ALBEMARLE SQ,CHARLOTTESVILLE,...,97016,Application of blood vessel compression or dec...,N,192,36,192,13.550989583,63.1125,9.6764583333,10.506927083
6,2137027,1215943535,BRUMITT,TOM,B,DO,M,I,70 DOCTORS PARK,CAPE GIRARDEAU,...,20610,Aspiration and/or injection of large joint or ...,N,21,19,21,45.971904762,164.57142857,36.036190476,37.77952381
7,6169160,1629160551,GALBREATH,RONALD,G,M.D.,M,I,12522 E. LAMBERT ROAD,WHITTIER,...,G0008,Administration of influenza virus vaccine,N,52,50,52,29.33,50,28.74,25.32
8,5086226,1518929124,BOONE,RALPH,M,D.O.,M,I,1215 DUNN AVE,JACKSONVILLE,...,80061,"Blood test, lipids (cholesterol and triglyceri...",N,73,68,73,15.510410959,76,15.197945205,15.197945205
9,3900718,1396781134,METWEST INC,1396781134,No Initial,NaN,UNKNOWN,O,695 S BROADWAY,DENVER,...,84392,Urine sulfate (acid) level,N,19,16,19,6.51,29.65,6.38,6.38

In [17]:
# Replacing the missing Credentials of the Provider with Not Provided because it cannot be guessed
data["Credentials of the Provider"] = data["Credentials of the Provider"].fillna("Not Provided")

In [18]:
# Doing the final checks if there is any missing values
data.isna().sum()

index                                                       0
National Provider Identifier                                0
Last Name/Organization Name of the Provider                 0
First Name of the Provider                                  0
Middle Initial of the Provider                              0
Credentials of the Provider                                 0
Gender of the Provider                                      0
Entity Type of the Provider                                 0
Street Address 1 of the Provider                            0
City of the Provider                                        0
Zip Code of the Provider                                    0
State Code of the Provider                                  0
Country Code of the Provider                                0
Provider Type                                               0
Medicare Participation Indicator                            0
Place of Service                                            0
HCPCS Code                                                  0
HCPCS Description                                           0
HCPCS Drug Indicator                                        0
Number of Services                                          0
Number of Medicare Beneficiaries                            0
Number of Distinct Medicare Beneficiary/Per Day Services    0
Average Medicare Allowed Amount                             0
Average Submitted Charge Amount                             0
Average Medicare Payment Amount                             0
Average Medicare Standardized Amount                        0
dtype: int64

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   index                                                     100000 non-null  int64
 1   National Provider Identifier                              100000 non-null  int64
 2   Last Name/Organization Name of the Provider               100000 non-null  object
 3   First Name of the Provider                                100000 non-null  object
 4   Middle Initial of the Provider                            100000 non-null  object
 5   Credentials of the Provider                               100000 non-null  object
 6   Gender of the Provider                                    100000 non-null  object
 7   Entity Type of the Provider                               100000 non-null  object
 8   Street Address 1 of the Provider                          100000 non-null  object
 9   City of the Provider                                      100000 non-null  object
 10  Zip Code of the Provider                                  100000 non-null  float64
 11  State Code of the Provider                                100000 non-null  object
 12  Country Code of the Provider                              100000 non-null  object
 13  Provider Type                                             100000 non-null  object
 14  Medicare Participation Indicator                          100000 non-null  object
 15  Place of Service                                          100000 non-null  object
 16  HCPCS Code                                                100000 non-null  object
 17  HCPCS Description                                         100000 non-null  object
 18  HCPCS Drug Indicator                                      100000 non-null  object
 19  Number of Services                                        100000 non-null  object
 20  Number of Medicare Beneficiaries                          100000 non-null  object
 21  Number of Distinct Medicare Beneficiary/Per Day Services  100000 non-null  object
 22  Average Medicare Allowed Amount                           100000 non-null  object
 23  Average Submitted Charge Amount                           100000 non-null  object
 24  Average Medicare Payment Amount                           100000 non-null  object
 25  Average Medicare Standardized Amount                      100000 non-null  object
dtypes: float64(1), int64(2), object(23)
memory usage: 19.8+ MB

In [20]:
# Saving columns index 23, 24 and 25 into a variable name avg_amt
avg_amt = ["Average Medicare Allowed Amount", "Average Submitted Charge Amount", "Average Medicare Payment Amount"]

In [21]:
# Converting the data type of columns 23, 24, and 25 from object to float
data[avg_amt] = data[avg_amt].replace(',', '', regex=True).astype(float)

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   index                                                     100000 non-null  int64
 1   National Provider Identifier                              100000 non-null  int64
 2   Last Name/Organization Name of the Provider               100000 non-null  object
 3   First Name of the Provider                                100000 non-null  object
 4   Middle Initial of the Provider                            100000 non-null  object
 5   Credentials of the Provider                               100000 non-null  object
 6   Gender of the Provider                                    100000 non-null  object
 7   Entity Type of the Provider                               100000 non-null  object
 8   Street Address 1 of the Provider                          100000 non-null  object
 9   City of the Provider                                      100000 non-null  object
 10  Zip Code of the Provider                                  100000 non-null  float64
 11  State Code of the Provider                                100000 non-null  object
 12  Country Code of the Provider                              100000 non-null  object
 13  Provider Type                                             100000 non-null  object
 14  Medicare Participation Indicator                          100000 non-null  object
 15  Place of Service                                          100000 non-null  object
 16  HCPCS Code                                                100000 non-null  object
 17  HCPCS Description                                         100000 non-null  object
 18  HCPCS Drug Indicator                                      100000 non-null  object
 19  Number of Services                                        100000 non-null  object
 20  Number of Medicare Beneficiaries                          100000 non-null  object
 21  Number of Distinct Medicare Beneficiary/Per Day Services  100000 non-null  object
 22  Average Medicare Allowed Amount                           100000 non-null  float64
 23  Average Submitted Charge Amount                           100000 non-null  float64
 24  Average Medicare Payment Amount                           100000 non-null  float64
 25  Average Medicare Standardized Amount                      100000 non-null  object
dtypes: float64(4), int64(2), object(20)
memory usage: 19.8+ MB

In [23]:
# Converting the data type of column 'Average Medicare Standardized Amount' from object to float
data["Average Medicare Standardized Amount"] = data["Average Medicare Standardized Amount"].replace(',', '', regex=True).astype(float)

In [24]:
# Confirming the conversions

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   index                                                     100000 non-null  int64
 1   National Provider Identifier                              100000 non-null  int64
 2   Last Name/Organization Name of the Provider               100000 non-null  object
 3   First Name of the Provider                                100000 non-null  object
 4   Middle Initial of the Provider                            100000 non-null  object
 5   Credentials of the Provider                               100000 non-null  object
 6   Gender of the Provider                                    100000 non-null  object
 7   Entity Type of the Provider                               100000 non-null  object
 8   Street Address 1 of the Provider                          100000 non-null  object
 9   City of the Provider                                      100000 non-null  object
 10  Zip Code of the Provider                                  100000 non-null  float64
 11  State Code of the Provider                                100000 non-null  object
 12  Country Code of the Provider                              100000 non-null  object
 13  Provider Type                                             100000 non-null  object
 14  Medicare Participation Indicator                          100000 non-null  object
 15  Place of Service                                          100000 non-null  object
 16  HCPCS Code                                                100000 non-null  object
 17  HCPCS Description                                         100000 non-null  object
 18  HCPCS Drug Indicator                                      100000 non-null  object
 19  Number of Services                                        100000 non-null  object
 20  Number of Medicare Beneficiaries                          100000 non-null  object
 21  Number of Distinct Medicare Beneficiary/Per Day Services  100000 non-null  object
 22  Average Medicare Allowed Amount                           100000 non-null  float64
 23  Average Submitted Charge Amount                           100000 non-null  float64
 24  Average Medicare Payment Amount                           100000 non-null  float64
 25  Average Medicare Standardized Amount                      100000 non-null  float64
dtypes: float64(5), int64(2), object(19)
memory usage: 19.8+ MB

In [25]:
# Saving columns 19, 20, and 21 into the variable name num_of_serv so as to convert them at once
num_of_serv = ["Number of Services", "Number of Medicare Beneficiaries", "Number of Distinct Medicare Beneficiary/Per Day Services"]

In [26]:
# Converting the variable from object data type to float data type
data[num_of_serv] = data[num_of_serv].replace(',', '', regex=True).astype(float)

In [27]:
# Converting the variable from float data type to integer data type
data[num_of_serv] = data[num_of_serv].astype(int)

In [28]:
# Doing the final confirmation
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   index                                                     100000 non-null  int64
 1   National Provider Identifier                              100000 non-null  int64
 2   Last Name/Organization Name of the Provider               100000 non-null  object
 3   First Name of the Provider                                100000 non-null  object
 4   Middle Initial of the Provider                            100000 non-null  object
 5   Credentials of the Provider                               100000 non-null  object
 6   Gender of the Provider                                    100000 non-null  object
 7   Entity Type of the Provider                               100000 non-null  object
 8   Street Address 1 of the Provider                          100000 non-null  object
 9   City of the Provider                                      100000 non-null  object
 10  Zip Code of the Provider                                  100000 non-null  float64
 11  State Code of the Provider                                100000 non-null  object
 12  Country Code of the Provider                              100000 non-null  object
 13  Provider Type                                             100000 non-null  object
 14  Medicare Participation Indicator                          100000 non-null  object
 15  Place of Service                                          100000 non-null  object
 16  HCPCS Code                                                100000 non-null  object
 17  HCPCS Description                                         100000 non-null  object
 18  HCPCS Drug Indicator                                      100000 non-null  object
 19  Number of Services                                        100000 non-null  int64
 20  Number of Medicare Beneficiaries                          100000 non-null  int64
 21  Number of Distinct Medicare Beneficiary/Per Day Services  100000 non-null  int64
 22  Average Medicare Allowed Amount                           100000 non-null  float64
 23  Average Submitted Charge Amount                           100000 non-null  float64
 24  Average Medicare Payment Amount                           100000 non-null  float64
 25  Average Medicare Standardized Amount                      100000 non-null  float64
dtypes: float64(5), int64(5), object(16)
memory usage: 19.8+ MB

In [29]:
# Checking for any duplicates
data.duplicated().sum()

np.int64(0)